### ISSUE TITLE
Check if the paths in installer are all valid

### ISSUE THREAD

**Issue by ThiaudioTT** [ThiaudioTT/hoi4-presence#13]
Add checking if paths in installer are all valids.

If it isn't valid, ask the user to enter the path again.

![image](https://github.com/ThiaudioTT/hoi4-presence/assets/43919529/a17c00ac-6785-4c78-84b1-b571f221b999)

Obs:
Checking if the path is valid isn't enough, we already do it. Check if the path contains the game and the others resources that the presence uses (if any) and asks the user until we find a real valid path.

**Comment by kiozet** [comment]
Hey, buddy! If you haven't solved the problem yet, please assigne it to me!

**Comment by ThiaudioTT** [comment]
> Hey, buddy! If you haven't solved the problem yet, please assigne it to me!

Hi! Thank you so much!

It appears that is already a pull request on, but it doesn't solve the problem. Feel free to open another or work on the same PR.
