### ISSUE TITLE
Issue on launch

### ISSUE THREAD

**Issue by ignatius65** [ThiaudioTT/hoi4-presence#18]
Game launches fine, however error messages appear and appears to be accessing wrong file-path, user profile is not called User? (e.g. "Users/User/etc." should be "Users/actualusername/etc."
![Capture](https://github.com/ThiaudioTT/hoi4-presence/assets/61355544/260fdb91-328c-4098-9e45-59bec753b6de)
![Capture2](https://github.com/ThiaudioTT/hoi4-presence/assets/61355544/c2d2aa63-054f-4f2a-8082-db361aa90101)

**Comment by ThiaudioTT** [comment]
Thank you for opening this issue.

This could be a problem with your OS and the file opening hoi4presence.

What's your users in `C:\Users`?
