### ISSUE TITLE
Is 'in menus' a good title, when starting the game? I think not

### ISSUE THREAD

**Issue by ThiaudioTT** [ThiaudioTT/hoi4-presence#35]
https://github.com/ThiaudioTT/hoi4-presence/blob/bd92a27a6247460e39c6820db68dbc779630f9b8/src/discordRPC/hoi4RPC.py#L21

I think it should be "Playing hoi4" or something. 

Maybe a good idea is to add some intelligence and display other things as well.

**Comment by Gpriman** [comment]
"Preparing for war..." 👀
