### ISSUE TITLE
[BUG] Hoi4 Logo not appearing in large-image

### ISSUE THREAD

**Issue by joshkosh55** [ThiaudioTT/hoi4-presence#40]
I don't know if it's because of this mod called "The Road to 56" but is there any way to fix this to show the country your playing as?
I tried many ways to solve it maybe I am dumb lol  I can't seem to find a solution. Cheers!
![Screenshot 2024-06-27 230410](https://github.com/ThiaudioTT/hoi4-presence/assets/174028708/84c0f668-6eab-4202-84ff-e9a9a1116719)

**Comment by ThiaudioTT** [comment]
It seems that the logo we use doesn't exist anymore:

https://hoi4.paradoxwikis.com/images/8/8a/HoI4_icon.png


@joshkosh55 When you play as the Philippines in vanilla, everything works as expected?

**Comment by joshkosh55** [comment]
Thanks for responding! I haven't been able to try it in vanilla yet because I just downloaded it, and the first thing I did was download mods, so I should've tried that first lol . I'll let you know if it works when I come home.

**Comment by joshkosh55** [comment]
So I just tested it with vanilla, and sadly, it's still like that with no image being shown. I tried playing as switzerland and USA since I thought maybe the program was unable to detect less popular countries but still no images.

**Comment by ThiaudioTT** [comment]
> I tried playing as switzerland and USA since I thought maybe the program was unable to detect less popular countries but still no images.

Did you save the game? When you save the game, after 30s it updates the presence. 

The issue is just with the game logo in large image, I think. 


I will work on a fix asap

**Comment by joshkosh55** [comment]
> Did you save the game? When you save the game, after 30s it updates the presence.

Yep, I tried that and also waited for a month in-game just to be sure, sadly, still no image.

> The issue is just with the game logo in large image, I think.

yeah, everything works fine as expected and also thanks for fixing this bro,

**Comment by ThiaudioTT** [comment]
> yeah, everything works fine as expected and also thanks for fixing this bro,

Np, thank you for using it!

Everything is fixed, you need to update the presence now to release v1.2.2.
