### ISSUE TITLE
Create an "all in one" file

### ISSUE THREAD

**Issue by ThiaudioTT** [ThiaudioTT/hoi4-presence#9]
This will help with the release packages. Make a CMAKE/Makefile using batch, or something, to compile all the files in one folder.

**Comment by Wolfmyths** [comment]
Would it be fine if we still used PyInstaller to compile all the files into one folder?

This can be done with the `-F --onefile` flag. And in return will output a [.spec](https://pyinstaller.org/en/stable/usage.html) file.

The .spec file can be easily configured so we don't have to go through the hassle of using CLI to bundle everything. The spec file is also written in Python so it's not like a regular text file.

**Comment by ThiaudioTT** [comment]
> Would it be fine if we still used PyInstaller to compile all the files into one folder?

Yes. The only problem in not compiling in one file is that we use some dependencies I think (I don't remember).

> When we want to export the program now with a .spec file we can do pyinstaller name.spec and it will do all the work for us.

Good, we need to test it.

**Comment by ThiaudioTT** [comment]
Working on it, and testing using .spec
